### ISSUE TITLE
home command bug

### ISSUE THREAD

**Issue by darcane** [darcane/TurtleWalker#3]
**home** command does not protect **pen** state.

**Comment by livacengiz** [comment]
bu nedir?

**Comment by darcane** [comment]
`home` yazdığın zaman komut olarak bulunduğu yerden ilk noktaya geri dönmesi gerekiyo. şimdilik bunu destekliyo ama geri dönerken eğer `pen` true state'inde ise çizgi çekmesi gerekiyo

> The home command causes the turtle to return to the center of the screen. It may leave ink behind when it does this.

**Comment by darcane** [comment]
home bug fixed
